// <auto-generated />
namespace AsegurarSA.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class comisarias : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(comisarias));
        
        string IMigrationMetadata.Id
        {
            get { return "201311032308053_comisarias"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
